[tox]
envlist = py39
skipsdist = True

[testenv]
deps =
    pytest
    pytest-cov
    ruff
    -e .
commands = 
    ruff check gendiff tests
    pip install -e .
    pytest --cov=gendiff --cov-report=xml --cov-config=tox.ini --cov-branch
